server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  ssl:
    enabled: false
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/funseven
    username: user
    password: password
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
client:
  ads:
    url: <url>
    username: <username>
    password: <password>